export enum Role {
  COLLECTOR = 'COLLECTOR',
  EXPERT = 'EXPERT',
  ADMIN = 'ADMIN'
}

export enum CoinStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  ASSIGNED = 'ASSIGNED',
  IN_EVALUATION = 'IN_EVALUATION',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED'
}
